name: git

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

        run: | 
          git pull 
          
