name: Deploy on push

on:
push:
branches: [ staging ]

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Install SSH Key
uses: aitindia/ssh-key-action@v2
with:
key: ${{ secrets.SSH_PRIVATE_KEY }}

known_hosts: ${{ secrets.SSH_HOST }}

- name: Pull
run: ssh git-user@3.22.119.118 "cd website/aitindia && /usr/bin/git pull origin master”

